public enum NodeType
{
    BaseNode = 1,
    BehaviourNode,
    DecoratorNode,
    ConditionNode,
    ConditionWaitNode,
    ExcelNode,
    ActionNode,
    WaitNode,
    SequenceNode,
    SelectorNode,
    NotDecorator,
    FailIfRunningDecorator,
    RunningIfFailDecorator,
    LoopNode,
    RandomNode,
    PriorityNode,
    ParallelNode,
    ParallelNodeAny,
    EventNode,
    WhileNode,
    IfNode,
    WeightSelectNode
}